# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraChatRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraChatRoom
  pod 'AgoraAudio_iOS'
  pod 'AgoraRtm_iOS'
  pod 'LeanCloud'

end
